---
title: label_acs_pums
description: |
  Label ACS microdata in memory.
categories: ["ACS and CPS microdata utilities"]
---

## Description

`label_acs_pums` labels [American Community Survey public use microdata](https://www.census.gov/programs-surveys/acs/microdata.html) in memory using information retrieved from the ACS PUMS data dictionaries.

Only 2013 and later ACS microdata are supported.

By default, the data dictionaries and intermediate labeling .do files are cached. Specify `use_cache` to use the cached files rather than re-downloading and re-generating them.

::: callout-caution
Variable and value labels generated by `label_acs_pums` are not a substitute for the ACS microdata data dictionary. Labels may be truncated and some important information may be missing.
:::

## Syntax

``` stata
label_acs_pums, year(integer) [options]
```

| Option | Description |
|----|----|
| `year(integer)` | Year of dataset in memory; 2013 or later. |
| `sample(integer)` | Sample of dataset in memory; 1 for the 1-year sample (the default) or 5 for the 5-year sample. |
| `use_cache` | Use data from the cache if it exists. An internet connection is required when `use_cache` is not specified or cached data does not exist. |

: {tbl-colwidths="\[30,70\]"}
