---
title: svyset_acs
description: |
  Declare the survey design in ACS microdata.
categories: ["ACS and CPS microdata utilities"]
---

## Description

`svyset_acs` is a shortcut program to declare the survey design for ACS microdata in memory with `svyset`.

For example, `svyset_acs, record_type(person)` is equivalent to `svyset [iw=pwgtp], vce(sdr) sdrweight(pwgtp1-pwgtp80) mse`.

## Syntax

``` stata
svyset_acs, record_type(string) [options]
```

| Option | Description |
|----|----|
| `record_type(string)` | Record type of the dataset in memory; "person" or "household". Abbreviations "h", "hhld", "hous", "p", and "pers" are also accepted. |
| `n_years(integer)` | Specifies the number of years of ACS microdata in memory; default is 1. If `n_years()` is greater than 1, `svyset_acs` will generate copies of the weights variables divided by this number and use those weights in `svyset`. |

: {tbl-colwidths="\[30,70\]"}

## Examples

Survey set household-level ACS microdata.

``` stata
svyset_acs, record_type(hhld)
```

Survey set a dataset comprised of 3 years of 1-year person-level ACS microdata.

``` stata
svyset_acs, record_type(person) n_years(3)
```
