project:
  type: website
  pre-render: "copy_src.R"
  resources:
    - "src"

website:
  title: "cbppstatautils"
  site-url: https://centeronbudget.github.io/cbpp-stata-utils/
  repo-url: https://github.com/CenterOnBudget/cbpp-stata-utils/
  bread-crumbs: false
  page-footer: "Copyright © 2024 Center on Budget and Policy Priorities." 
  navbar:
    search: true
    logo: logo-grid-white.png
    logo-alt: ""
    left: 
      - index.qmd
      - reference.qmd
      - news.qmd
    tools:
      - icon: github
        href: https://github.com/CenterOnBudget/cbpp-stata-utils
        aria-label: GitHub
  
format:
  html:
    theme: 
      - cosmo
      - styles.scss
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 200px
    toc: true

callout-appearance: simple



